-- Idempotent index baseline reconstructed from the linked project's pg_indexes inventory.
-- Existing schema migrations may already create some of these names; IF NOT EXISTS prevents duplicates.
-- Production already records this version; this file restores source parity only.
begin;

CREATE INDEX IF NOT EXISTS idx_admin_access_profiles_active ON public.admin_access_profiles USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_admin_access_profiles_created_by ON public.admin_access_profiles USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_admin_access_profiles_expiration ON public.admin_access_profiles USING btree (access_expires_at);
CREATE INDEX IF NOT EXISTS idx_admin_access_profiles_level ON public.admin_access_profiles USING btree (access_level);
CREATE INDEX IF NOT EXISTS idx_admin_access_profiles_updated_by ON public.admin_access_profiles USING btree (updated_by);
CREATE INDEX IF NOT EXISTS admin_audit_logs_created_idx ON public.admin_audit_logs USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_target_user_id ON public.admin_audit_logs USING btree (target_user_id);
CREATE INDEX IF NOT EXISTS idx_admin_invitations_email ON public.admin_invitations USING btree (lower(email));
CREATE INDEX IF NOT EXISTS idx_admin_invitations_invited_by ON public.admin_invitations USING btree (invited_by);
CREATE INDEX IF NOT EXISTS idx_admin_invitations_invited_user_id ON public.admin_invitations USING btree (invited_user_id);
CREATE INDEX IF NOT EXISTS idx_admin_invitations_status ON public.admin_invitations USING btree (status);
CREATE INDEX IF NOT EXISTS idx_announcements_created_by ON public.announcements USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_app_settings_updated_by ON public.app_settings USING btree (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS categories_name_key ON public.categories USING btree (name);
CREATE UNIQUE INDEX IF NOT EXISTS categories_slug_key ON public.categories USING btree (slug);
CREATE INDEX IF NOT EXISTS idx_conversation_participants_user ON public.conversation_participants USING btree (user_id);
CREATE INDEX IF NOT EXISTS conversations_talent_id_idx ON public.conversations USING btree (talent_id);
CREATE INDEX IF NOT EXISTS idx_conversations_created ON public.conversations USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_conversations_project_id ON public.conversations USING btree (project_id);
CREATE UNIQUE INDEX IF NOT EXISTS countries_code_key ON public.countries USING btree (code);
CREATE UNIQUE INDEX IF NOT EXISTS countries_name_key ON public.countries USING btree (name);
CREATE INDEX IF NOT EXISTS idx_favorites_client ON public.favorites USING btree (client_id);
CREATE INDEX IF NOT EXISTS idx_favorites_talent ON public.favorites USING btree (talent_id);
CREATE INDEX IF NOT EXISTS idx_kora_payouts_transaction_id ON public.kora_payouts USING btree (transaction_id);
CREATE INDEX IF NOT EXISTS idx_kora_transactions_client ON public.kora_transactions USING btree (client_id);
CREATE INDEX IF NOT EXISTS idx_kora_transactions_manager ON public.kora_transactions USING btree (manager_id);
CREATE UNIQUE INDEX IF NOT EXISTS kora_transactions_reference_key ON public.kora_transactions USING btree (reference);
CREATE INDEX IF NOT EXISTS idx_manager_talent_invitations_manager_id ON public.manager_talent_invitations USING btree (manager_id);
CREATE INDEX IF NOT EXISTS idx_manager_talent_invitations_talent_id ON public.manager_talent_invitations USING btree (talent_id);
CREATE UNIQUE INDEX IF NOT EXISTS manager_talent_invitations_token_key ON public.manager_talent_invitations USING btree (token);
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON public.messages USING btree (conversation_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON public.notifications USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON public.payments USING btree (status);
CREATE INDEX IF NOT EXISTS idx_payments_subscription_id ON public.payments USING btree (subscription_id);
CREATE INDEX IF NOT EXISTS idx_payments_user ON public.payments USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_payments_validated_by ON public.payments USING btree (validated_by);
CREATE UNIQUE INDEX IF NOT EXISTS payments_reference_unique_idx ON public.payments USING btree (reference);
CREATE INDEX IF NOT EXISTS idx_portfolio_items_talent ON public.portfolio_items USING btree (talent_id);
CREATE INDEX IF NOT EXISTS profiles_city_idx ON public.profiles USING btree (city);
CREATE INDEX IF NOT EXISTS profiles_company_idx ON public.profiles USING btree (company);
CREATE INDEX IF NOT EXISTS profiles_last_seen_idx ON public.profiles USING btree (last_seen DESC);
CREATE INDEX IF NOT EXISTS profiles_role_idx ON public.profiles USING btree (role);
CREATE INDEX IF NOT EXISTS profiles_suspended_idx ON public.profiles USING btree (is_suspended);
CREATE INDEX IF NOT EXISTS idx_project_talents_talent ON public.project_talents USING btree (talent_id);
CREATE INDEX IF NOT EXISTS idx_projects_client ON public.projects USING btree (client_id);
CREATE INDEX IF NOT EXISTS idx_projects_due_date ON public.projects USING btree (due_date);
CREATE INDEX IF NOT EXISTS idx_projects_manager ON public.projects USING btree (manager_id);
CREATE INDEX IF NOT EXISTS idx_projects_status ON public.projects USING btree (status);
CREATE INDEX IF NOT EXISTS idx_reports_resolved_by ON public.reports USING btree (resolved_by);
CREATE INDEX IF NOT EXISTS idx_requests_client ON public.requests USING btree (client_id);
CREATE INDEX IF NOT EXISTS idx_requests_manager ON public.requests USING btree (manager_id);
CREATE INDEX IF NOT EXISTS idx_requests_project ON public.requests USING btree (project_id);
CREATE INDEX IF NOT EXISTS idx_requests_status ON public.requests USING btree (status);
CREATE INDEX IF NOT EXISTS idx_requests_talent ON public.requests USING btree (talent_id);
CREATE INDEX IF NOT EXISTS idx_reviews_reviewer_id ON public.reviews USING btree (reviewer_id);
CREATE INDEX IF NOT EXISTS reviews_client_idx ON public.reviews USING btree (client_id);
CREATE INDEX IF NOT EXISTS reviews_project_idx ON public.reviews USING btree (project_id);
CREATE INDEX IF NOT EXISTS reviews_talent_idx ON public.reviews USING btree (talent_id);
CREATE UNIQUE INDEX IF NOT EXISTS skills_name_key ON public.skills USING btree (name);
CREATE INDEX IF NOT EXISTS idx_subscriptions_user ON public.subscriptions USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS subscriptions_one_current_per_user_idx ON public.subscriptions USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_talent_profile_skills_skill_id ON public.talent_profile_skills USING btree (skill_id);
CREATE INDEX IF NOT EXISTS idx_talent_profiles_category ON public.talent_profiles USING btree (category_id);
CREATE INDEX IF NOT EXISTS idx_talent_profiles_country ON public.talent_profiles USING btree (country_id);
CREATE INDEX IF NOT EXISTS idx_talent_profiles_managed_by ON public.talent_profiles USING btree (managed_by);
CREATE INDEX IF NOT EXISTS idx_talent_profiles_status ON public.talent_profiles USING btree (status);
CREATE INDEX IF NOT EXISTS idx_talent_profiles_visible ON public.talent_profiles USING btree (is_visible);
CREATE INDEX IF NOT EXISTS user_consents_user_id_idx ON public.user_consents USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_verification_requests_manager_id ON public.verification_requests USING btree (manager_id);
CREATE INDEX IF NOT EXISTS idx_verification_requests_reviewed_by ON public.verification_requests USING btree (reviewed_by);
CREATE INDEX IF NOT EXISTS idx_verification_requests_talent_id ON public.verification_requests USING btree (talent_id);

commit;
